[project]
authors = ["Edmund Miller <git@edmundmiller.dev>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "IFN_heterogeneity"
platforms = ["linux-64"]
version = "0.1.0"

[feature.rnaseq.dependencies]
star = "2.7.3a.*"
samtools = "1.10.*"

[feature.rnaseq.tasks]
align = { cmd = "01_STAR_align.sh", cwd = "RNA-seq" }
filter = { cmd = "02_samtools_filter.sh", depends-on = ["align"], cwd = "RNA-seq" }

[environments]
rnaseq = ["rnaseq"]
