[project]
authors = ["Edmund Miller <git@edmundmiller.dev>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "IFN_heterogeneity"
platforms = ["linux-64"]
version = "0.1.0"

[feature.rnaseq.dependencies]
star = "2.7.3a.*"
samtools = "1.10.*"
r-dplyr = ">=1.0.10,<2"
r-tidyr = ">=1.2.1,<2"
r-ggplot2 = ">=3.3.6,<4"
r-magrittr = ">=2.0.3,<3"
r-devtools = ">=2.4.4,<3"
bioconductor-rsubread = ">=2.4.3,<3"
bioconductor-rsamtools = ">=2.6.0,<3"
"bioconductor-txdb.hsapiens.ucsc.hg38.knowngene" = ">=3.10.0,<4"
bioconductor-deseq2 = ">=1.30.1,<2"
bioconductor-edger = ">=3.32.1,<4"
bioconductor-soggi = ">=1.10.4,<2"
r-markdown = ">=1.7,<2"

[feature.rnaseq.tasks]
align = { cmd = "01_STAR_align.sh", cwd = "RNA-seq" }
filter = { cmd = "02_samtools_filter.sh", depends-on = ["align"], cwd = "RNA-seq" }
index = { cmd = "03_bam_index.sh", depends-on = ["filter"], cwd = "RNA-seq" }
DEG_analysis = { cmd = "Rscript -e \"rmarkdown::render('04_DEG_analysis.Rmd')\"", depends-on = ["filter", "index"], cwd = "RNA-seq" }  # TODO outputs = ["report.html"]

[environments]
rnaseq = ["rnaseq"]
